storage:
  protocol: _____
  host: _____
  port: _____
  username: _____
  password: _____
  sid: _____
  input_path: _____
  output_path: _____
  hdf5_path: _____
  overwrite_downloads: false # перезаписывать ли ЭЭГ файлы при загрузке из хранилища
  overwrite_uploads: false # перезаписывать ли сегменты при загрзке в хранилище
  create_remote_parents: true # создавать ли несуществующие директории при загрузке в хранилище

logging:
  logs_dir: "./temp/logs"

segmentation:
  edf_dir: "./temp/download_upload/edf_input"
  cleaned_edf: "./temp/preprocessing/cleaned_edf"
  csv_dir: "./temp/preprocessing/output_csv"
  segments_dir: "./temp/preprocessing/output_segments"
  blocks_dir: "./temp/preprocessing/output_blocks"
  block_duration: 5.0

targets:
  targets_csv: "./info_data/prepared/studies.csv"

database:
  host: _____
  port: _____
  database: _____
  username: _____
  password: _____

processing:
  bandpass_filter: [0.5, 45]
  notch_filter: [50, 60]
  segment_min_duration: 1.0 # минимальная длительность сегмента (сек)
  block_length: 5.0 # длина блока (сек)
  bad_channel_threshold: 0.8 # порог для "плохих" каналов
  limit_file_size: true # включает ограничение на размер обрабатываемого файла
  file_size_limit_mb: 730 # максимальный размер файла в MB

hdf5:
  compression: gzip
  compression_opts: 4
  chunks: True